java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/UNIT.TYPE testVALUE/PRIMITIVE/UNIT.VALUE testVALUE/PRIMITIVE/UNIT.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/BOOL.TYPE testVALUE/PRIMITIVE/BOOL_true.VALUE testVALUE/PRIMITIVE/BOOL_false.VALUE 

java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/NAT.TYPE testVALUE/PRIMITIVE/NAT_123.VALUE testVALUE/PRIMITIVE/NAT_23.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/CHAR.TYPE testVALUE/PRIMITIVE/CHAR_s.VALUE testVALUE/PRIMITIVE/CHAR_t.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/REAL05.TYPE testVALUE/PRIMITIVE/REAL_208.VALUE testVALUE/PRIMITIVE/REAL_209.VALUE

