java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/UNIT.TYPE testVALUE/PRIMITIVE/UNIT.VALUE testVALUE/PRIMITIVE/UNIT.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/BOOL.TYPE testVALUE/PRIMITIVE/BOOL_true.VALUE testVALUE/PRIMITIVE/BOOL_false.VALUE 
java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/NAT.TYPE testVALUE/PRIMITIVE/NAT_123.VALUE testVALUE/PRIMITIVE/NAT_23.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/CHAR.TYPE testVALUE/PRIMITIVE/CHAR_s.VALUE testVALUE/PRIMITIVE/CHAR_t.VALUE


java -cp lib dcprototype.DIFF -d testTYPE/PRIMITIVE/REAL05.TYPE testVALUE/PRIMITIVE/REAL_208.VALUE testVALUE/PRIMITIVE/REAL_209.VALUE



java -cp lib dcprototype.DIFF -d testTYPE/PRODUCT/PAIR.TYPE testVALUE/PRODUCT/PAIR_1.VALUE testVALUE/PRODUCT/PAIR_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/PRODUCT/PAIR_UNIT.TYPE testVALUE/PRODUCT/PAIR_UNIT.VALUE testVALUE/PRODUCT/PAIR_UNIT.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/PRODUCT/TRIPLE.TYPE testVALUE/PRODUCT/TRIPLE_1.VALUE testVALUE/PRODUCT/TRIPLE_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/PRODUCT/PRODUCT.TYPE testVALUE/PRODUCT/PRODUCT_1.VALUE testVALUE/PRODUCT/PRODUCT_2.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/UNION/UNION_LEFT_LIST_CHAR.TYPE testVALUE/UNION/UNION_left_LIST_CHAR_1.VALUE testVALUE/UNION/UNION_left_LIST_CHAR_2.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/UNION/UNION.TYPE testVALUE/UNION/UNION_left_NAT_1.VALUE testVALUE/UNION/UNION_left_NAT_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/UNION/UNION.TYPE testVALUE/UNION/UNION_right_PAIR_1.VALUE testVALUE/UNION/UNION_right_PAIR_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/UNION/UNION_UNION.TYPE testVALUE/UNION/UNION_UNION_left_1.VALUE testVALUE/UNION/UNION_UNION_left_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/UNION/UNION_UNION.TYPE testVALUE/UNION/UNION_UNION_left_1.VALUE testVALUE/UNION/UNION_UNION_right.VALUE


java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_LIST_NAT.TYPE testVALUE/REC/REC_LIST_NAT_1.VALUE testVALUE/REC/REC_LIST_NAT_2.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_LIST_NAT.TYPE testVALUE/REC/REC_LIST_NAT_1.VALUE testVALUE/REC/REC_LIST_NAT_3.VALUE
java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_TREE_NAT.TYPE testVALUE/REC/REC_TREE_NAT_1.VALUE testVALUE/REC/REC_TREE_NAT_2.VALUE

