java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_LIST_NAT.TYPE testVALUE/REC/REC_LIST_NAT_1.VALUE testVALUE/REC/REC_LIST_NAT_2.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_LIST_NAT.TYPE testVALUE/REC/REC_LIST_NAT_1.VALUE testVALUE/REC/REC_LIST_NAT_3.VALUE

java -cp lib dcprototype.DIFF -d testTYPE/REC/REC_TREE_NAT.TYPE testVALUE/REC/REC_TREE_NAT_1.VALUE testVALUE/REC/REC_TREE_NAT_2.VALUE

