
TYPE: SET(PRODUCT(size.REAL(0.5)*name.LIST(CHAR)))
TypeT 1:
{(size.57.6(0.5),name.[A,G,T,M]),(size.78.9(0.5),name.[M,B,T,T]),(size.56.8(0.5),name.[A,F,G,G])}
TypeT 2:
{(size.78.9(0.5),name.[M,B,T,A,T]),(size.57.7(0.5),name.[A,G,T,M])}
Delta :
[0.15,0.15]
DeltaSet: [DeltaProduct:(size.Chg.(78.9(0.5),57.7(0.5)), name.[0.25,0.25], DeltaList: [ins.A, ins.G, ins.T, cpy.M, del.B, del.T, del.T]), DeltaProduct:(size.Chg.(57.6(0.5),78.9(0.5)), name.[0.22,0.22], DeltaList: [del.A, del.G, del.T, cpy.M, ins.B, ins.T, ins.A, ins.T]), del.(size.56.8(0.5),name.[A,F,G,G])]
