
TYPE: SET(LIST(PRODUCT(size.REAL(0.5)*name.CHAR)))
TypeT 1:
{[(size.57.7(0.5),name.A),(size.79.0(0.5),name.M)],[(size.12.0(0.5),name.B),(size.66.5(0.5),name.P),(size.13.6(0.5),name.G)]}
TypeT 2:
{[(size.57.7(0.5),name.A),(size.78.9(0.5),name.M)],[(size.12.0(0.5),name.B),(size.66.5(0.5),name.T),(size.13.6(0.5),name.G)]}
Delta :
[0.2,0.2]
DeltaSet: [[0.5,0.5], DeltaList: [DeltaProduct:(size.Chg.(57.7(0.5),57.7(0.5)), name.cpy.A), del.(size.79.0(0.5),name.M), ins.(size.78.9(0.5),name.M)], [0.0,0.0], DeltaList: [ins.(size.12.0(0.5),name.B), del.(size.12.0(0.5),name.B), del.(size.66.5(0.5),name.P), del.(size.13.6(0.5),name.G), ins.(size.66.5(0.5),name.T), ins.(size.13.6(0.5),name.G)]]
